# Generated by Django 4.2.6 on 2023-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Фентези'), (2, 'Фантастика'), (3, 'Детектив')], null=True),
        ),
    ]
